version: "3"
services:
  server:
    container_name: c12y_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: c12y/server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  client:
    container_name: c12y_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: c12y/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/build
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  admin:
    container_name: c12y_admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: c12y/admin
    ports:
      - "4000:4000"
    volumes:
      - ./admin:/usr/src/admin
      - /usr/src/admin/node_modules
      - /usr/src/admin/build
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
