# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    pull_request:
        types: [closed]
        branches: [master]

jobs:
    deploy:
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: SSH and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd /var/www/c12y.com/c12y
                      git pull origin master
                      cd server
                      npm ci
                      pm2 restart c12y-server
                      cd ../client
                      npm ci
                      npm run build
                      cd ../admin
                      npm ci
                      npm run build
